### PR TITLE
Fix do not drop path when valid

### PR DESCRIPTION
**Pull request by smadbe**
## Description

Fixes 2 (related) issues:
1. when a temp user navigate to path he hasn't explored yet (if he receives a link not at the root)... (depending on the order of the requests) most of the time the navigation cannot be load in the left menu as parents have not be started (to reproduce: for instance go to [this page](https://dev.algorea.org/en/activities/by-id/1980584647557587953;path=4702,4102;parentAttempId=0) as a temp user (incognito/private mode))
2. when there was a failure because a path has not been started, the path was completely dropped to restart a new one... but this may cause to change path while it is not what we want

## Test cases

- [ ] Case 1:
  1. Given I am a **temp** user on a new incognito/private tab
  2. Then I open network panel 
  3. When I go to [a page not at root](https://dev.algorea.org/branch/fix-do-not-drop-path-when-valid/en/activities/by-id/1980584647557587953;path=4702,4102;parentAttempId=0)
  4. Then I see in the url bar that the path is not dropped and rebuilt
  5. Then I see the left menu is loaded 

- [ ] Case 2: The previous case is still working (invalid numeric path (forbidden))
  1. Given I am a **temp** user on a new incognito/private tab
  3. When I go to [a page with an invalid path](https://dev.algorea.org/branch/fix-do-not-drop-path-when-valid/en/activities/by-id/1980584647557587953;path=123,456;parentAttempId=0)
  4. Then I see in the url bar that the path is dropped and rebuilt to a correct one "4702, 4102"

- [ ] Case 3: The previous case is still working (char path)
  1. Given I am a **temp** user on a new incognito/private tab
  3. When I go to [a page with an invalid path](https://dev.algorea.org/branch/fix-do-not-drop-path-when-valid/en/activities/by-id/1980584647557587953;path=AB,cd;parentAttempId=0)
  4. Then I see in the url bar that the path is dropped and rebuilt to a correct one "4702, 4102"

### CODE REVIEW

**Comment by smadbe** [comment]
@Iloveall could you check what's wrong with the e2e test ? I don't understand the problem.

**Comment by Iloveall** [comment]
> @Iloveall could you check what's wrong with the e2e test ? I don't understand the problem.

Redirect doesn't work as before - https://dev.algorea.org/en/activities/by-id/1625159049301502151;path=invalid,path;parentAttempId=0

**Comment by smadbe** [comment]
> 
> Redirect doesn't work as before - https://dev.algorea.org/en/activities/by-id/1625159049301502151;path=invalid,path;parentAttempId=0
> 
> After: https://dev.algorea.org/branch/fix-do-not-drop-path-when-valid/en/activities/by-id/1625159049301502151;path=invalid,path;parentAttempId=0

I do not see any difference between your two link. 🤷‍♂️

**Comment by smadbe** [comment]
Ok, good. Could you review it @Iloveall ?

**Review by Iloveall — APPROVED** [review]

**Pull request merged**
