### PR TITLE
Make tabs global

### PR DESCRIPTION
**Pull request by smadbe**
## Description

Move the item tabs globally so that they can put (in a future issue) in the tab bar.

## Test cases

- [x] Case 1: Chapter basics
  1. Given I am the usual user
  2. When I go to [a chapter](https://dev.algorea.org/branch/make-tabs-global/en/a/7523720120450464843;p=7528142386663912287;a=0)
  3. And I land on the content of the "content" tab
  4. Then I see tabs "stats", "history", "dependencies" and "parameters" tabs with appropriate routing.
  5. The "stats" as the chapter view (for users)
  6. I see no other tabs

- [x] Case 2: Stat tab with observing a group
  1. Given I am the usual user
  2. When I go to [a content while observing a group](https://dev.algorea.org/branch/make-tabs-global/en/a/7528142386663912287;p=;pa=0?watchedGroupId=4462192261130512818&watchUser=0)
  3. I see one "stats" tab
  4. And it displays the matrix view

- [x] Case 3: Stat tab with observing a group
  1. Given I am the usual user
  2. When I go to [a content while observing a group](https://dev.algorea.org/branch/make-tabs-global/en/a/7528142386663912287;p=;pa=0?watchedGroupId=752024252804317630&watchUser=1)
  3. I see one "stats" tab
  4. And it displays the chapter view

- [x] Case 4: "Stat" tab hidden 
  1. Given I am the usual user
  2. When I go to a [task which hides the progress](https://dev.algorea.org/branch/make-tabs-global/en/a/6319140447749005365;p=7528142386663912287,7523720120450464843;a=0)
  3. I do not see any "stats" nor "history" tab
  4. I see the "content" tab has been replaced by the task tabs 
  5. I can switch freely among the task tab
  6. Switching the "dependencies" tab and switching back to the "Statement" does not reload the task

- [x] Case 5: Tab bar hidden if only one tab 
  1. Given I am the **demo** user
  2. And I test locally
  3. And I disable forum (`forumUrl` not set)
  4. When I go to a [task which hides the progress, have one tab and I do not have more perm on the content](http://localhost:4200/a/2004936693550411739;p=7528142386663912287,7523720120450464843;pa=0)
  5. I do not see tab bar
  6. I see the "content" of the only tab

-  [x] Case 6: Nav between item keep the same tab selected. Tab disappear when not supposed to be visible when leaving it.
  1. Given I am the usual user
  2. When I go to the [stats tab of a item](https://dev.algorea.org/branch/make-tabs-global/en/a/7523720120450464843;p=7528142386663912287;a=0/progress/chapter-user-progress)
  3. I select "Blockly Basic Task " 
  4. I am still on the "stats" even if this tab is not supposed to appear
  7. If I go to the "history" tab, the "stats" tab disappear

-  [x] Case 7: Visiting task with "edit-children" enabled
  1. Given I am the usual user
  2. When I go to [a chapter in edit-children mode](https://dev.algorea.org/branch/make-tabs-global/en/a/7523720120450464843;p=7528142386663912287;a=0/edit-children)
  3. I select "Blockly Basic Task " 
  4. The task loads normally

Unable to test for now: if on tab which disappear when resizing (task tabs can be created / removed on resize)... should fallback to a correct page.

Still a bug? Sometimes the content is empty (blank) ... had several times but cannot reproduce: 
- when switching user, on 7523720120450464843 for instance -> there is no current Tab so the ngrxlet does not run

### CODE REVIEW

**Comment by smadbe** [comment]
@Iloveall : There is still the design of the bar to be done (apply the same style as now). The active task is the one in red.

**Comment by Iloveall** [comment]
I can't reproduce Case 5

**Comment by smadbe** [comment]
> I can't reproduce Case 5

Hum.. now the forum has been introduced, that does not happen anymore. The only way to test for now is probably to disable the forum locally.

**Comment by smadbe** [comment]
Update: I have update the url (localhost->branch) and the description of case 5 to test locally.

**Review by Iloveall — APPROVED** [review]

**Comment by smadbe** [comment]
Bug: 

- as the usual user
- I visit this [task, forum tab](/a/6379723280369399253;p=7528142386663912287,7523720120450464843;a=0/forum/others)
- unexpected: the task loads in background and once loaded, the tab switches to "statement"

**Comment by smadbe** [comment]
> Bug:
> 
>     * as the usual user
> 
>     * I visit this [task, forum tab](/a/6379723280369399253;p=7528142386663912287,7523720120450464843;a=0/forum/others)
> 
>     * unexpected: the task loads in background and once loaded, the tab switches to "statement"

Fixed by commit 599a83b

**Comment by smadbe** [comment]
> Still a bug? Sometimes the content is empty (blank) ... had several times but cannot reproduce

This should be solved by ae3efc1

**Pull request merged**
