### PR TITLE
Changes design for common popup

### LINKED ISSUE #1580: New Design: Confirmation tooltip
## Overview

Change design for confirmation tooltip

UI_confirmation_tooltip

## Acceptance criteria
- [ ] Make it fit to our design
- [ ] Adjust colors and fonts size
- [ ] Change design for buttons
- [ ] Replace with new icons

### PR DESCRIPTION
**Pull request by Iloveall**
## Description

Fixes #1580

## Notes (out of scope, known isues, hints for reviewing code, ...)  (optional)

...

## Test cases

- [ ] Case 1:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/branch/new-design/confirmation-tooltip/en/groups/mine)
  3. And I click on leave group button
  4. Then I see changed design for popup

- [ ] Case 2:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/branch/new-design/confirmation-tooltip/en/groups/by-id/1376052779483255449;p=/managers)
  3. And I select first row
  4. And I click on delete button
  5. Then I see changed design for popup

- [ ] Case 3:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/branch/new-design/confirmation-tooltip/en/groups/by-id/1546088973873922141;p=/members)
  3. And I click on "Sub-groups" tab
  4. And I select first row
  5. Then I click on delete button
  6. Then I see changed design for popup

### CODE REVIEW

**Comment by smadbe** [comment]
The link of "case 3" is wrong.

**Review by smadbe — CHANGES_REQUESTED** [review]
Is the default selection (with its blue contour) on purpose? 
Screenshot 2024-02-28 at 10 41 38

At the end, the button borders are not sharp. Is there a way to improve that? (I think you've already fixed that somewhere else) 
Screenshot 2024-02-28 at 10 42 02

**Comment by smadbe** [comment]
> > Is the default selection (with its blue contour) on purpose?

> By default blue, but it was red in prev version as well, kind very danger operation I think

I meant: do we want a default selection? I am not sure that is good idea (in terms on design at least, it is not great ;-))

**Comment by Iloveall** [comment]
> > > Is the default selection (with its blue contour) on purpose?
> 
> > By default blue, but it was red in prev version as well, kind very danger operation I think
> 
> I meant: do we want a default selection? I am not sure that is good idea (in terms on design at least, it is not great ;-))

Ah, you mean focus state, okay I'll remove it then

**Comment by Iloveall** [comment]
> Is the default selection (with its blue contour) on purpose? Screenshot 2024-02-28 at 10 41 38
> 
> At the end, the button borders are not sharp. Is there a way to improve that? (I think you've already fixed that somewhere else) Screenshot 2024-02-28 at 10 42 02

I've removed focus border. Do you still have second effect? I can't reproduce it

**Review by smadbe — APPROVED** [review]
The unsharp borders, I have only on my mac, when the browser window is on my external screen (non-retina). Not sure it has to be fixed but I thought you already fixed that in the past.

Still there: 
Screenshot 2024-03-11 at 11 15 15
Screenshot 2024-03-11 at 11 15 52
Screenshot 2024-03-11 at 11 16 52

If you cannot fix that, that's not a big deal.

**Comment by smadbe** [comment]
Is it on purpose that the arrow is blue while the popup in white?

**Comment by Iloveall** [comment]
> Is it on purpose that the arrow is blue while the popup in white?

Changed to white

**Pull request merged**
