### PR TITLE
Implement task auto height

### LINKED ISSUE #862: Resize task when the window is resized and on entering/leaving full frame
**Describe the bug**
The blockly task are not resized when entering "full frame". As a result, the space saved by the removed header is not available for the task.
For instance: https://dev.algorea.org/en/#/activities/by-id/784078458149384669;path=4702,1352246428241737349,314613032161178344,34689573454313988;parentAttempId=0/details as a temp user:

Screenshot 2022-01-07 at 10 51 44

Or when there are lots of space: 
Screenshot 2022-01-07 at 10 53 57

Expected, as on https://parcours.algorea.org/contents/4707-4702-1352246428241737349-314613032161178344-34689573454313988-784078458149384669/:
Screenshot 2022-01-07 at 10 55 02

**Expected behavior**
Same as in parcours.algorea.org/.

### PR DESCRIPTION
**Pull request by ThomasJuster**
## Description

Fixes #862 

## Notes (out of scope, known issues, hints for reviewing code, ...)  (optional)

There still look to be some place at the bottom, but that's a 5+ rem padding of app main section. If you want it to be less, maybe it could be another issue to assign to Aleksandr.
If I remove the app main section padding from the height calculus, the app can be scrolled a bit but it's only white space, which can be considered ok as well. You tell me.

## Test cases

- [ ] Case 1:
  1. Given I am an anonymous user
  2. When I go to [this activity](https://dev.algorea.org/branch/feat/task-auto-height/en/#/activities/by-id/784078458149384669;path=4702,1352246428241737349,314613032161178344,34689573454313988;parentAttempId=0/details)
  3. Then I see the task height is adapted to the viewport
  4. And I resize the browser
  5. Then I see the task height automatically matches the height of the viewport
  6. And I collapse the left menu
  7. Then I see the task height automatically matches the height of the viewport
  8. And I expand the left menu
  9. Then I see the task height automatically matches the height of the viewport

- [ ] Case 2: (no regression test)
  1. Given I am any user
  2. When I go to [this activity](https://dev.algorea.org/branch/feat/task-auto-height/en/#/activities/by-id/837046206729127555;path=4702,1352246428241737349,314613032161178344;parentAttempId=0/details)
  3. Then I see the task height is set by the task itself, scroll is at body level and not iframe-container level
  4. And I resize the browser
  5. Then (again) I see the task height is set by the task itself, scroll is at body level and not iframe-container level
  6. And I collapse the left menu
  7. Then (again) I see the task height is set by the task itself, scroll is at body level and not iframe-container level
  8. And I expand the left menu
  9. Then (again) I see the task height is set by the task itself, scroll is at body level and not iframe-container level

### CODE REVIEW

**Review by smadbe — CHANGES_REQUESTED** [review]
Not sure the example task is well adapted.
- lots of space under it (maybe normal?)
Screenshot 2022-01-11 at 16 34 10

-  after menu uncollapse:
Screenshot 2022-01-11 at 16 35 05
 
Test scenarios should also include long tasks where the platform scrolling is required, to check they are not broken.

**Comment by ThomasJuster** [comment]
> lots of space under it (maybe normal?)

That's what I explained in the notes:

> There still look to be some place at the bottom, but that's a 5+ rem padding of app main section. If you want it to be less, maybe it could be another issue to assign to Aleksandr.
If I remove the app main section padding from the height calculus, the app can be scrolled a bit but it's only white space, which can be considered ok as well. You tell me.

**Comment by ThomasJuster** [comment]
> Test scenarios should also include long tasks where the platform scrolling is required, to check they are not broken.

I added the test case 2 for that

**Comment by ThomasJuster** [comment]
> after menu uncollapse:

fixed

**Comment by smadbe** [comment]
> > lots of space under it (maybe normal?)
> 
> That's what I explained in the notes:
> 
> > There still look to be some place at the bottom, but that's a 5+ rem padding of app main section. If you want it to be less, maybe it could be another issue to assign to Aleksandr.
> > If I remove the app main section padding from the height calculus, the app can be scrolled a bit but it's only white space, which can be considered ok as well. You tell me.

Sorry, I missed that.

**Review by smadbe — APPROVED** [review]
👍

**Pull request merged**
