### PR TITLE
Changes primeng tab menu with custom tabs

### PR DESCRIPTION
**Pull request by Iloveall**
## Description

Fixes [#1458](https://github.com/France-ioi/AlgoreaFrontend/issues/1458)

## Notes (out of scope, known isues, hints for reviewing code, ...)  (optional)

...

## Test cases

- [ ] Case 1:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/branch/feature/custom-tabs-component/en/a/6379723280369399253;p=7523720120450464843;a=0)
  3. Then I see new tabs with same design in header
  4. Then I click on next tab
  5. Then I see content of next tab

- [ ] Case 2:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/branch/feature/custom-tabs-component/en/a/1293400563985240032;p=7523720120450464843;a=0)
  3. Then I see new tabs with same design under content

- [ ] Case 3:
  1. Given I am the usual user
  2. From narrow size of window (mobile)
  3. When I go to [this page](https://dev.algorea.org/branch/feature/custom-tabs-component/en/a/6379723280369399253;p=7523720120450464843;a=0)
  4. Then I see new tabs with arrows in header
  5. Then I click on next button until end
  6. Then I see the next button is disappeared and prev button is appeared
  7. Then I click on prev button unit start
  8. Then I see the prev button is disappeared and next button is appeared

- [ ] Case 4:
  1. Given I am the usual user
  2. From narrow size of window (mobile)
  3. When I go to [this page](https://dev.algorea.org/branch/feature/custom-tabs-component/en/a/1293400563985240032;p=7523720120450464843;a=0)
  4. Then I see new tabs with arrows under content
  5. Then I click on next button until end
  6. Then I see the next button is disappeared and prev button is appeared
  7. Then I click on prev button unit start
  8. Then I see the prev button is disappeared and next button is appeared

- [ ] Case 5:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/branch/feature/custom-tabs-component/en/a/6379723280369399253;p=7523720120450464843;a=0)
  3. Then I see new tabs with same design in header
  4. And I change width of window to narrow
  5. Then I see the next arrow button is appeared
  6. Then I change width of window to desktop
  7. Then I see the next arrow button is disappeared

### CODE REVIEW

**Comment by smadbe** [comment]
The arrow is not always visible where it should, is it "on purpose"?

https://github.com/France-ioi/AlgoreaFrontend/assets/1053150/60bebd2e-a420-4540-8690-3895ea59c84e

**Comment by smadbe** [comment]
When we arrive at the end left or right, there is slight delay before the arrow disappear, is it on purpose?

https://github.com/France-ioi/AlgoreaFrontend/assets/1053150/68a664ab-4587-4f05-b7b8-c95d82d0b057

**Comment by smadbe** [comment]
Would it be arrow button more aligned with the design than what we have. Primeng version looks nice. (can be more narrow, as the one you did)

We have: 
Screenshot 2023-11-14 at 09 06 44

Primeng version:
Screenshot 2023-11-14 at 09 06 57

**Comment by Iloveall** [comment]
> The arrow is not always visible where it should, is it "on purpose"?

The idea to avoid overflow by arrows if user accidentally scrolled a bit. I've decreased the gap, please try again

> When we arrive at the end left or right, there is slight delay before the arrow disappear, is it on purpose?

There is debounce for avoid computing during the scroll. I've decreased the value, please try again

**Review by smadbe — APPROVED** [review]
Look great 🎉

**Pull request merged**
