### PR TITLE
Changes design for common confirm dialog

### LINKED ISSUE #1561: New Design: Confirmation message
## Overview

Change design for confirmation message

UI_confirmation_message

## Acceptance criteria
- [ ] Make it fit to our design
- [ ] Change buttons design
- [ ] Adjust fonts
- [ ] Replace with new icons
- [ ] Improves modal colours

### PR DESCRIPTION
**Pull request by Iloveall**
## Description

Fixes #1561

## Notes (out of scope, known isues, hints for reviewing code, ...)  (optional)

...

## Test cases

- [ ] Case 1:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/branch/new-design/confirmation-message/en/a/4925914885021677676;p=54644880678791414;a=0/parameters)
  3. And I click on "Delete this item" button
  4. Then I see changed design for confirmation modal

- [ ] Case 2:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/branch/new-design/confirmation-message/en/a/54644880678791414;p=;a=0/edit-children)
  3. And I do changes in list
  4. Then I click on next tab
  5. Then I see changed design for confirmation modal

- [ ] Case 3:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/branch/new-design/confirmation-message/en/groups/by-id/2132623576446659559;p=/settings)
  3. And I click on "Delete this group" button
  4. Then I see changed design for confirmation modal

- [ ] Case 4:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/branch/new-design/confirmation-message/en/groups/by-id/2516747935037112838;p=/managers)
  3. And I click on "Edit manager" button
  4. Then I do downgrade permissions
  5. And I click on "Proceed" button
  6. Then I see changed design for confirmation modal

### CODE REVIEW

**Comment by smadbe** [comment]
Again here:
 
This is not sharp on my second screen:
Screenshot 2024-03-11 at 11 21 38
While this is sharp:
Screenshot 2024-03-11 at 11 22 02

**Review by smadbe — APPROVED** [review]

**Comment by smadbe** [comment]
[auto-generated message] E2E test report on: https://algorea-static.s3.eu-central-1.amazonaws.com/branch/new-design/confirmation-message/playwright-report/index.html

**Comment by smadbe** [comment]
[auto-generated message] E2E test report on: https://algorea-static.s3.eu-central-1.amazonaws.com/branch/new-design/confirmation-message/playwright-report/index.html

**Comment by Iloveall** [comment]
> Again here:
> 
> This is not sharp on my second screen: Screenshot 2024-03-11 at 11 21 38 While this is sharp: Screenshot 2024-03-11 at 11 22 02

I've removed border line (grey) on red button, it's only difference between regular button and this one. Please check

**Pull request merged**
