### PR TITLE
Changes design for messages component

### LINKED ISSUE #1624: New Design: Message component
## Overview

Improve design for message component.

Should we adjust this one component or get rid of it and to use toast notifier?

message-ui
message-ui2

## Acceptance criteria
- [ ] Change bg color
- [ ] Adjust space
- [ ] Adjust fonts
- [ ] Change icons

### PR DESCRIPTION
**Pull request by Iloveall**
## Description

Fixes #1624 

## Notes (out of scope, known isues, hints for reviewing code, ...)  (optional)

...

## Test cases

- [ ] Case 1:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/branch/new-design/message-component/en/groups/by-id/8791610698648252339;p=/members)
  3. And I do scroll to "Invite users" section
  4. Then I type "notfound" as login
  5. And I click on "Invite" button
  6. Then I see new design for failed message

- [ ] Case 2:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/branch/new-design/message-component/en/groups/by-id/1069803384095693918;p=/members)
  3. And I do scroll to "Invite users" section
  4. Then I type "notfound, usr_5p020x2thuyu" as logins
  5. And I click on "Invite" button
  6. Then I see new design for info and failed messages

- [ ] Case 3:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/branch/new-design/message-component/en/groups/by-id/7618436449137122738;p=/members)
  3. And I do scroll to "Invite users" section
  4. Then I type "usr_5p020x2thuyu" as login
  5. And I click on "Invite" button
  6. Then I see new design for success message

### CODE REVIEW

**Comment by smadbe** [comment]
[auto-generated message] E2E test report on: https://algorea-static.s3.eu-central-1.amazonaws.com/branch/new-design/message-component/playwright-report/index.html

**Comment by smadbe** [comment]
[auto-generated message] E2E test report on: https://algorea-static.s3.eu-central-1.amazonaws.com/branch/new-design/message-component/playwright-report/index.html

**Comment by smadbe** [comment]
[auto-generated message] E2E test report on: https://algorea-static.s3.eu-central-1.amazonaws.com/branch/new-design/message-component/playwright-report/index.html

**Review by smadbe — COMMENTED** [review]
For case 3, do you have a success ? I get an error.

**Comment by Iloveall** [comment]
> For case 3, do you have a success ? I get an error.

Just tried, it works for me with `usr_5p020x2thuyu`

Screenshot at Mar 11 20-27-56

**Comment by smadbe** [comment]
Ok sorry, I was still on the group (link) of the 1st case

**Review by smadbe — APPROVED** [review]

**Pull request merged**
