### PR TITLE
publish result to LTI

### LINKED ISSUE #840: (LTI) Send score when it changes
## Overview

In order to integrate with LTI as a provider, we need to send the user score back to the LTI platform.

See [milestone description](https://github.com/France-ioi/AlgoreaFrontend/milestone/2) and our [LTI workflow](https://france-ioi.github.io/algorea-devdoc/task_platforms/lti/).

## Acceptance criteria

- [ ] each time there is a score change in a task, [request the backend](https://france-ioi.github.io/algorea-devdoc/api/#operation/resultPublish) to publish the updated results to LTI (the `item_id` is the one from the chapter (`content_id`) as the LTI consumer just know about the chapter!)

### PR DESCRIPTION
**Pull request by ThomasJuster**
## Description

Fixes #840 

## Notes (out of scope, known issues, hints for reviewing code, ...)  (optional)

I have a doubt about how to handle an error while publishing a result to LTI, what I did was displaying a toast saying:
- if 403 forbidden (probably the http cookie token has expired ?):  "You might be unauthenticated anymore, please try relaunching the exercise. If the problem persits contact us."
- For any other error: "An unknown error occurred while publishing your result".
The second message is unsatisfying in my opinion, but I didn't find any relevant option.

## Test cases

:warning: Test must be done in localhost because the login module disallows redirecting to branch apps…  :confused: 

- [ ] Case 1:
  1. Given I am the LTI demo user
  2. When I go to [the moodle platform](http://moodletest.algorea.org/course/view.php?id=3)
  3. And I open network panel
  4. And I re-submit the first level
  5. Then I see the publish request is sent … but I got an error :unamused: 

- [ ] Case 2:
  1. Given I am the usual user
  2. When I go directly to the [same task](https://dev.algorea.org/branch/feat/lti-send-score/en/#/activities/by-id/6379723280369399253;path=4702,1625159049301502151,5207993233955027100;attempId=0/details) not through LTI
  3. An I open my network panel
  4. And I complete first level
  5. Then I see no publish request is sent

### CODE REVIEW

**Comment by smadbe** [comment]
The publish service now works, however the red error message is still displayed.

**Comment by smadbe** [comment]
> I have a doubt about how to handle an error while publishing a result to LTI, what I did was displaying a toast saying:
> 
>     * if 403 forbidden (probably the http cookie token has expired ?):  "You might be unauthenticated anymore, please try relaunching the exercise. If the problem persits contact us."
> 
>     * For any other error: "An unknown error occurred while publishing your result".
>       The second message is unsatisfying in my opinion, but I didn't find any relevant option.


looks good to me

**Comment by smadbe** [comment]
As it is quite urgent and other parts of the workflow have been fixed, I will merge it myself.

**Review by smadbe — APPROVED** [review]

**Comment by smadbe** [comment]
@ThomasJuster  I am going to merge it but I recommend you still review my changes.

**Comment by ThomasJuster** [comment]
I checked the last 2 commits, all good :heavy_check_mark:

**Pull request merged**
