### PR TITLE
Improves view answer logic for logs

### LINKED ISSUE #1672: Check that the user can watch item answer for displaying view/reload answer buttons
## Overview
itemActivityLogForItem & itemActivityLogForAllItems services now have a `can_watch_item_answer` attribute which let us know if the user can "view answer" or "reload answer". Use that properties to improve log views.

## Acceptance criteria
- [ ] in the item progress (log)  page, allow to view/reload  the answer ONLY if `can_watch_item_answer` is true : that replace the ` meta.canWatchAnswers` checks that might now be correct for item children
- [ ] in the group progress (log)  page, `allowToViewAnswer` should not be limited `log.participant.id === currentUserProfile.groupId` anymore but `log.participant.id === currentUserProfile.groupId || can_watch_item_answer`
- [ ] in the user's progress (log) page, same as groups

### PR DESCRIPTION
**Pull request by Iloveall**
## Description

Fixes #1672 

## Notes (out of scope, known isues, hints for reviewing code, ...)  (optional)

...

## Test cases

- [ ] Case 1:
  1. Given I am the usual user
  2. When I go to [item page](https://dev.algorea.org/branch/feature/check-user-can-watch-item-answer/en/a/home;pa=0/progress/history)
  3. Then I see "Reload answer" links

- [ ] Case 2:
  1. Given I am the usual user
  2. When I go to [current user page](https://dev.algorea.org/branch/feature/check-user-can-watch-item-answer/en/groups/users/670968966872011405)
  3. Then I see "View answer" links

- [ ] Case 3:
  1. Given I am the usual user
  2. When I go to [group page](https://dev.algorea.org/branch/feature/check-user-can-watch-item-answer/en/groups/by-id/4035378957038759250;p=)
  3. Then I see "View answer" links for other users

- [ ] Case 4:
  1. Given I am the usual user
  2. When I go to [other user page](https://dev.algorea.org/branch/feature/check-user-can-watch-item-answer/en/groups/users/752024252804317630)
  3. Then I see "View answer" links for another user

### CODE REVIEW

**Comment by smadbe** [comment]
[auto-generated message] E2E test report on: https://algorea-static.s3.eu-central-1.amazonaws.com/branch/feature/check-user-can-watch-item-answer/playwright-report/index.html

**Review by smadbe — APPROVED** [review]
👍 
We should start to add playwright test everything it makes sense. Here it does, the "problem" is that we have to make sure we test on data that will not change (or test a property of the UI which is always valid)

**Comment by smadbe** [comment]
[auto-generated message] E2E test report on: https://algorea-static.s3.eu-central-1.amazonaws.com/branch/feature/check-user-can-watch-item-answer/playwright-report/index.html

**Comment by Iloveall** [comment]
> 👍 We should start to add playwright test everything it makes sense. Here it does, the "problem" is that we have to make sure we test on data that will not change (or test a property of the UI which is always valid)

I've add new e2e tests with mocked data way

**Review by smadbe — APPROVED** [review]
👍

**Pull request merged**
