### PR TITLE
New design/group page 2

### PR DESCRIPTION
**Pull request by Iloveall**
## Description

Fixes #...

## Notes (out of scope, known isues, hints for reviewing code, ...)  (optional)

...

## Test cases

- [ ] Case 1:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/branch/new-design/group-page-2/en/groups/by-id/4035378957038759250;p=/members?watchedGroupId=none&watchUser=0)
  3. Then I see changed design for header of group page
  4. And I see new design for group indicator component

- [ ] Case 2:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/branch/new-design/group-page-2/en/groups/by-id/460263955289148254;p=)
  3. Then I see changed design for leave group button

### CODE REVIEW

**Review by smadbe — CHANGES_REQUESTED** [review]
I think I already had this issue: the button is a bit blurry:
Screenshot 2023-06-12 at 18 17 26

**Comment by Iloveall** [comment]
> I think I already had this issue: the button is a bit blurry: Screenshot 2023-06-12 at 18 17 26

Mb this is because of color (not fully white)? Could you try again please

**Comment by smadbe** [comment]
> Mb this is because of color (not fully white)? Could you try again please

Looks good now 👍

**Review by smadbe — CHANGES_REQUESTED** [review]
As the crown means "manager", there should not be a crown in such a case.
Screenshot 2023-06-14 at 10 34 06

**Pull request merged**
